version: '3'
services:
  web:
    image: greyabiwon/springboot:v3
    ports:
      - 80:80
    volumes:
      - ./html:/usr/share/nginx/html
    deploy:
      replicas: 3
    restart_policy:
      condition: any
